### ISSUE TITLE
eat own dog food

### ISSUE THREAD

**Issue by Guria** [leonardoanalista/cz-customizable#13]
We can use `cz-customizable` instead `cz-conventional-changelog`. I will prepare a PR but I need list of scopes

**Comment by leonardoanalista** [comment]
+1. As expected npm doesn't allow packaged to depend on itself... a work around would be good.

**Comment by Guria** [comment]
We do not have to. Just provide me list of scopes and I'll do the job

**Comment by leonardoanalista** [comment]
because `cz-customizable` is pretty small, I actually can't thing about a list of scopes. At work, we have multiple projects and about 7 scope options per project. The list kind of grows as scopes are related to the features driven by business. 
I think for us in this project, the `type` is already self explanatory. What do you think?

**Comment by Guria** [comment]
Okay. So I will introduce ability for custom and empty scopes in #16 and will switch project to use itself.
